FROM python:3.12-slim AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY docs ./docs

RUN sphinx-build -b html docs/source docs/build/html

FROM nginx:alpine

COPY --from=builder /app/docs/build/html /usr/share/nginx/html
EXPOSE 80
